# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Build & Upload artifacts

defaults:
    run:
        shell: bash

env:
    CI: true
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144

on:
    workflow_call:
        inputs:
            artifact-path:
                description: Path pattern to include in upload
                required: true
                type: string
            artifact-upload:
                description: Include uploading artifact step
                required: false
                type: boolean

            exclude:
                description: Pattern of paths to exclude
                default: "{**/*.map,**/node_modules/**}"
                required: false
                type: string
            include:
                description: Pattern of paths to include
                required: true
                type: string

            script-build:
                description: Executable command script to build the output
                required: true
                type: string

jobs:
    build-job:
        name: Build with compression report
        runs-on: ${{ matrix.os }}
        timeout-minutes: 3
        strategy:
            matrix:
                OS: [ubuntu-latest]
            fail-fast: true
        steps:
            # https://github.com/terminal-nerds/setup-nodejs-with-pnpm
            - name: Setup Node.js with pnpm
              uses: terminal-nerds/setup-nodejs-with-pnpm-action@v1
              with:
                  skip-installing-dependencies: true

            - name: Execute build task with compression report
              # https://github.com/preactjs/compressed-size-action
              uses: preactjs/compressed-size-action@v2
              with:
                  build-script: ${{ inputs.script-build }}
                  exclude: ${{ inputs.exclude }}
                  pattern: ${{ inputs.include }}
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload built output to GitHub Actions workflow artifacts
              # https://github.com/actions/upload-artifact
              uses: actions/upload-artifact@v3
              if: ${{ inputs.artifact-upload }}
              with:
                  if-no-files-found: error
                  name: build-output
                  path: ${{ inputs.artifact-path }}
