# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Greetings

defaults:
    run:
        shell: bash

env:
    CI: true

on:
    workflow_call:

# Remove default permissions of `GITHUB_TOKEN` for security reasons
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
    greeting:
        name: Greet first time contributors
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: Read the markdown template
              # https://github.com/juliangruber/read-file-action
              uses: juliangruber/read-file-action@v1
              id: template
              with:
                  path: "./.github/templates/greetings.md"

            - name: Create a Pull Request comment
              # https://github.com/actions/first-interaction
              uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pr-message: ${{ steps.template.outputs.content }}
