# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Node.js job

defaults:
    run:
        shell: bash

env:
    CI: true

on:
    workflow_call:
        inputs:
            step-name:
                required: true
                type: string
            run:
                required: true
                type: string

jobs:
    nodejs_job:
        name: Node.js job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to ${{ github.repository }} repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Setup the latest pnpm version
              # https://github.com/pnpm/action-setup
              uses: pnpm/action-setup@v2.1.0
              with:
                  version: latest

            - name: Setup Node.js LTS version
              # https://github.com/actions/setup-node
              uses: actions/setup-node@v2
              with:
                  cache: pnpm
                  node-version: lts/*

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: ${{ inputs.step-name }}
              run: ${{ inputs.run }}
        timeout-minutes: 5
