# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Run Node.js script

on:
    workflow_call:
        inputs:
            download-build:
                default: false
                description: Download built output from the workflow artifacts
                required: false
                type: boolean

            job-name:
                description: Name of the job
                required: true
                type: string

            step-name:
                description: Name of the step for a better understanding of the logs
                required: true
                type: string

            run:
                description: Command to execute
                required: true
                type: string

defaults:
    run:
        shell: bash

env:
    CI: true
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144

jobs:
    nodejs-script:
        name: Run ${{ inputs.job-name }}
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            # https://github.com/terminal-nerds/setup-nodejs-with-pnpm
            - name: Setup Node.js with pnpm
              uses: terminal-nerds/setup-nodejs-with-pnpm-action@v1
              with:
                  download-build: ${{ inputs.download-build }}

            - name: ${{ inputs.step-name }}
              run: ${{ inputs.run }}
