# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Release / Changesets

on:
    workflow_call:
        secrets:
            NPM_TOKEN:
                description: Token for npmjs.com registry publishing
                required: true

defaults:
    run:
        shell: bash

env:
    CI: true
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

# Remove default permissions of `GITHUB_TOKEN` for security reasons
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
    contents: write
    pull-requests: write
    statuses: read

jobs:
    release:
        name: Changesets
        if: ${{
            github.ref_name == 'main' &&
            github.repository_owner == 'terminal-nerds'
            }}
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - name: Setup Node.js with pnpm
              # https://github.com/terminal-nerds/setup-nodejs-with-pnpm-action
              uses: terminal-nerds/setup-nodejs-with-pnpm-action@v1
              with:
                  download-build: true

            - name: Create changelogs, release, publish with Changesets
              # https://github.com/changesets/action
              uses: changesets/action@v1
              id: changesets
              with:
                  commit: "chore(Changesets): 🏷️ Versioning package(s)"
                  publish: pnpm changeset publish
                  title: "chore(Changesets): 🎉 Release package(s)"
                  version: pnpm changeset version
