# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Setup Node.js and pnpm

on:
    workflow_call:
        inputs:
            skip-installing-dependencies:
                default: false
                description: Skip installing Node.js dependencies with pnpm?
                required: false
                type: boolean

defaults:
    run:
        shell: bash

env:
    CI: true
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144

jobs:
    setup-nodejs:
        name: Setup Node.js and pnpm
        if: ${{
            github.ref_name == 'main' &&
            github.repository_owner == 'terminal-nerds'
            }}
        runs-on: ubuntu-latest
        timeout-minutes: 3
        steps:
            - name: Checkout to ${{ github.repository }} repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Setup the latest pnpm version
              # https://github.com/pnpm/action-setup
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Setup the latest Node.js LTS version
              # https://github.com/actions/setup-node
              uses: actions/setup-node@v3
              with:
                  cache: pnpm
                  node-version: lts/*

            - name: Install Node.js dependencies with pnpm
              if: ${{ !inputs.skip-installing-dependencies }}
              # https://pnpm.io/cli/install
              run: pnpm install --frozen-lockfile
