# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Snyk

on:
    workflow_call:
        secrets:
            SNYK_TOKEN:
                description: API key
                required: true

# Remove default permissions of `GITHUB_TOKEN` for security reasons
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
    actions: read
    contents: read
    security-events: write

jobs:
    snyk:
        name: Snyk
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              # https://github.com/actions/checkout
              uses: actions/checkout@v3

            - name: Run Snyk to check for vulnerabilities
              # https://github.com/snyk/actions/tree/master/node
              uses: snyk/actions/node@master
              # To make sure that SARIF upload gets called
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  # https://docs.snyk.io/features/snyk-cli/cli-reference
                  args: >
                      --all-projects
                      --sarif-file-output=snyk.sarif
                      --severity-threshold=high

            - name: Upload result to GitHub Code Scanning
              # https://github.com/github/codeql-action/
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: snyk.sarif
