# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Test

on:
    workflow_call:
        inputs:
            job-name:
                description: Name of the job
                required: true
                type: string

            script-test:
                description: Executable command script to run tests
                required: true
                type: string

            upload-coverage:
                description: Upload tests coverage results
                default: false
                required: false
                type: boolean

defaults:
    run:
        shell: bash

env:
    CI: true
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Remove default permissions of `GITHUB_TOKEN` for security reasons
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions: {}

jobs:
    test:
        name: ${{ inputs.job-name }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 3
        strategy:
            matrix:
                OS: [ubuntu-latest]
            fail-fast: true
        steps:
            # https://github.com/terminal-nerds/setup-nodejs-with-pnpm
            - name: Setup Node.js with pnpm
              uses: terminal-nerds/setup-nodejs-with-pnpm-action@v1.1.1
              with:
                  download-build: true

            - name: Execute the script for the tests
              run: ${{ inputs.script-test }}

            - name: Upload built output to GitHub Actions workflow artifacts
              # https://github.com/actions/upload-artifact
              uses: actions/upload-artifact@v3
              if: inputs.upload-coverage
              with:
                  if-no-files-found: error
                  name: tests-coverage
                  path: |
                      ./coverage/lcov.info
                      ./coverage/coverage-final.json
