# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Test

on:
    workflow_call:
        inputs:
            job-name:
                description: Name of the job
                required: true
                type: string

            script-test:
                description: Executable command script to run tests
                required: true
                type: string

            with-coverage:
                description: Run coverage analytics with Coveralls?
                default: false
                required: false
                type: boolean

        secrets:
            CC_TEST_REPORTER_ID:
                description: CodeClimate Quality test reporter ID for the coverage reports
                required: false

defaults:
    run:
        shell: bash

env:
    CI: true
    # Prevent possible memory leaks by setting limit
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    NODE_OPTIONS: --max-old-space-size=6144
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    test:
        name: ${{ inputs.job-name }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 3
        strategy:
            matrix:
                OS: [ubuntu-latest]
            fail-fast: true
        steps:
            # https://github.com/terminal-nerds/setup-nodejs-with-pnpm
            - name: Setup Node.js with pnpm
              uses: terminal-nerds/setup-nodejs-with-pnpm-action@v1

            - name: Execute the script for the tests
              run: ${{ inputs.script-test }}

            - name: Analyze the tests coverage report with Coveralls
              if: inputs.with-coverage
              # https://github.com/coverallsapp/github-action
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ env.GITHUB_TOKEN }}

            - name: Publish results to CodeClimate Quality
              if: inputs.with-coverage
              # https://github.com/paambaati/codeclimate-action
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
              uses: paambaati/codeclimate-action@v3.2.0
              with:
                  coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
                  debug: true
